CREATE DATABASE DB_Teste;

CREATE TABLE TB_PERFIL(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Nome VARCHAR(50) NOT NULL,
	Ativo BIT DEFAULT 0,
);

CREATE TABLE TB_FUNCIONALIDADE(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Nome VARCHAR(50) NOT NULL,
	Ativo BIT DEFAULT 0,
	PerfilId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_PERFIL (Id),
);

CREATE TABLE TB_USUARIO (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Nome VARCHAR(100) NOT NULL,
	Cpf VARCHAR(11) NOT NULL,
	Telefone VARCHAR(11) NOT NULL,
	Endereco VARCHAR(100) NOT NULL,
	Cep VARCHAR(8) NOT NULL,
	Sexo VARCHAR(20) NOT NULL,
	Ativo BIT DEFAULT 0,
	PerfilId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TB_PERFIL (Id),
);
