CREATE TABLE TB_FUNCIONALIDADE(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Ativo BIT DEFAULT 1 NOT NULL,
	PerfilId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_PERFIL (Id),
);

CREATE TABLE TB_PERFIL(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Ativo BIT DEFAULT 1 NOT NULL,
);

CREATE TABLE TB_USUARIO (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Cpf VARCHAR(11) NOT NULL,
	Telefone VARCHAR(14) NOT NULL,
	Endereco VARCHAR(100) NOT NULL,
	Cep VARCHAR(9) NOT NULL,
	Sexo VARCHAR(20) NOT NULL,
	Ativo BIT DEFAULT 1 NOT NULL,
	PerfilId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TB_PERFIL (Id),
);

CREATE TABLE TB_PERFIL_FUNCIONALIDADE(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	PerfilId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TB_PERFIL (Id),
	FuncionalidadeId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TB_FUNCIONALIDADE (Id),
);